services:
  master1:
    build:
      context: .
      target: hadoop-base
    image: hadoop-base
    hostname: master1
    container_name: master1
    ports:
      - "8888:8088"
      - "9878:9870"
    environment:
      - ROLE=master
      - MYID=1
    networks:
      - hadoopnet
    volumes:
      - zk1-data:/usr/local/zookeeper
      - jn1:/usr/local/hadoop/journal
      - hdfs-nn1:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn1"]
      interval: 10s
      timeout: 5s
      retries: 5

  master2:
    image: hadoop-base
    hostname: master2
    container_name: master2
    ports:
      - "8788:8088"
      - "9877:9870"
    environment:
      - ROLE=master
      - MYID=2
    networks:
      - hadoopnet
    volumes:
      - zk2-data:/usr/local/zookeeper
      - jn2:/usr/local/hadoop/journal
      - hdfs-nn2:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn2"]
      interval: 10s
      timeout: 5s
      retries: 5

  master3:
    image: hadoop-base
    hostname: master3
    container_name: master3
    ports:
      - "8688:8088"
      - "9876:9870"
    environment:
      - ROLE=master
      - MYID=3
    networks:
      - hadoopnet
    volumes:
      - zk3-data:/usr/local/zookeeper
      - jn3:/usr/local/hadoop/journal
      - hdfs-nn3:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn3"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: hadoop-base
    hostname: worker
    container_name: worker
    environment:
      - ROLE=worker
    networks:
      - hadoopnet
    volumes:
      - hdfs-dn1:/usr/local/hadoop/hdfs/datanode
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f DataNode && pgrep -f NodeManager"]
      interval: 10s
      timeout: 5s
      retries: 5
  hive-postgres:
    image: postgres:13
    hostname: hive-postgres
    container_name: hive-postgres
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    networks:
      - hadoopnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiveuser -d metastore"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    build: .
    image: hive
    hostname: hive-metastore
    container_name: hive-metastore
    environment:
      - ROLE=metastore
    networks:
      - hadoopnet
    healthcheck:
      test: ["CMD-SHELL", "jps | grep -E 'RunJar'"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      hive-postgres:
        condition: service_healthy
      master1:
        condition: service_healthy

  hive-server2:
    build: .
    image: hive
    hostname: hive-server2
    container_name: hive-server2
    environment:
      - ROLE=server2
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - hadoopnet
    depends_on:
      hive-metastore:
        condition: service_healthy
      worker:
        condition: service_healthy

  hmaster1:
    build:
      context: .
      target: hbase
    container_name: hmaster1
    hostname: hmaster1
    ports:
      - "16000:16000"  
      - "16010:16010"
    environment:
      - ROLE=h-master
    networks:
      - hadoopnet
    volumes:
      - hm1_data:/usr/local/hbase/data 
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy

  hmaster2:
    build:
      context: .
      target: hbase
    container_name: hmaster2
    hostname: hmaster2
    ports:
      - "16001:16000" 
      - "16011:16010"
    environment:
      - ROLE=h-master
    networks:
      - hadoopnet
    volumes:
      - hm2_data:/usr/local/hbase/data
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy

  regionserver1:
    build:
      context: .
      target: hbase
    hostname: regionserver1
    container_name: regionserver1
    ports:
      - "16020:16020"
    environment:
      - ROLE=region-server
    networks:
      - hadoopnet
    volumes:
      - hdfs-dn1:/usr/local/hadoop/hdfs/datanode
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    
  regionserver2:
    build:
      context: .
      target: hbase
    hostname: regionserver2
    container_name: regionserver2
    ports:
      - "16021:16020"  
    environment:
      - ROLE=region-server
    networks:
      - hadoopnet
    volumes:
      - hdfs-dn2:/usr/local/hadoop/hdfs/datanode
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy

networks:
  hadoopnet:
    driver: bridge

volumes:
  zk1-data:
  jn1:
  hdfs-nn1:
  zk2-data:
  jn2:
  hdfs-nn2:
  zk3-data:
  jn3:
  hdfs-nn3:
  hm1_data:
  hm2_data:
  hdfs-dn1:
  hdfs-dn2:
  postgres-data: